apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/officialarun/argocd-demos.git
    targetRevision: main
    path: cli_approach/apache # Path within the repo
  destination:
    server: https://192.168.49.2:8443 # Production cluster API server URL here, run `argocd cluster list` to get the URL
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    